# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'AppProgect' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppProgect
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'MBProgressHUD'
  pod 'FDFullscreenPopGesture'
  pod 'FMDB'
  pod 'RMessage','~> 2.3.0'
  pod 'ReactiveObjC', '~> 2.1.0'
  pod 'Reachability', '~> 3.2'
  pod 'WyhCornerRadius'
  pod 'YYKit'
  pod 'FORScrollViewEmptyAssistant'
  #pod 'DZNEmptyDataSet', '~> 1.8.1'
  #pod 'SDCycleScrollView'
  

end
